language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  - sbt +geohexJVM/test geohexJS/fullOptJS +geohexJVM/package
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

jdk:
  - openjdk8

after_success: >
  test "${TRAVIS_PULL_REQUEST}" = 'false' &&
  test "${TRAVIS_BRANCH}" = 'master' &&
  sh "$TRAVIS_BUILD_DIR/travis_credentials.sh" &&
  sbt +geohexJVM/publish geohexJS/npmPublish

env:
  global:
    # travis encrypt BINTRAY_USER=teraje..
    - secure: "So2BpFH6+heXQdlZ4utCJ+Ih8j9S92LWM7UFwzFgNdJoMpGyZfU/tTfDgPlpvCpncDJJzrhuXgJWmqmG1b0Ml8Z9KhUmIXTqG8lMNCnjzu9HpPwp770WbfMj5DlZmt1H60m+C346Nvnm9u7F53CEuRsM1fTGRPKbII+t2PX6ZPFqrDeHJPWLncCmBl1nyGRYjqXRsA9dG0AJHMlSE/7YaKOR+mKR8VkoTm2/HBuudvVk4327yCRhauO3ZO2Ad1mlJGVyogrpdPo5wElPyZQpYG1p+wgKZ2yaguJsuWTyXgbQUNHJk/VmIx0h2w+Fx5dSZFqLd5yj2R4HWVXDhw+iZWoVLzUTG59riLoOABSjcyinc2QYiGYsWq5teO3cqFcD9unyam9HmmO69D1pUzGR1PrdYRvdzdBjCLxnejUju/rcSORbqoGpooKEZpAkr49mHiPgg8BVRfQlU17nRjJ1DYl3n9KIUMNly70d4Ysf16znMcjJHCfmFACenLN/c7YafCYXrBGYMq6OZIUBnVfom9eb8S5ZgGaFdFR48GfM9nI1zE31AxBmfuNUVxpPRONf1lGFF27SSoqt1zBDZRpXrfqgI+Mfu/mZye3pnRdcqWjFGi6Y/mBMOJ9P6S2KXIpWqHsG7Pja4jwuhaizBQfFWI1qNqZdIzW8r+ZJStKEjn8="
    # travis encrypt BINTRAY_PASS=...
    - secure: "S7f5Qos51bpFjiMNxS7T9h4c+3DoWwqnhUwpmn0N0q+G+nQU0AgNmdNDYFl26d5gur7HA6Dd/+SGYgEu2NR4ZYDDgM5QdIuWGbJzeq/sjQkOmvvVUv1eGE2/RExytLmnKeH3lCtJR9KLoAakuDZ/EUS1Sr9skG3A4ivW4myJ2hK9oXFWgB71kSiNO5bKAv90+aVPqOvYzzdY8mnKZLSKpXLPVM3Nw9ow9G+e5SDGThhRXkXvm/S+sXdS6MX7AmDjXWxXugVowVqQH3QBV1djUh++Qd3KDQ49DRPw8uwEwMx78DnAo8vqEMPEPCjhYQfHK691QmvSu66HrIPZtqLAown3Gmk4gBuXYpBFXmA6HYpV6l4kjTycocQe1HlvUPNL3vI9LLMyXz5R9bAcnlTwI2FUxr/8QH8p5DfkZZ/C2jEWtGH9yDbdNrnExSECuXQf+dzIH9v/O6IVr9bavZ7XEz1TSmnfkADT5s2raBDkcXhysd8lDjxK6Ae9g6vIL0RJeK1FtoPtrtsXrlfQyXoLjom5PR3TF6V9DIKxlbGmXHXCOROi+cO/Ge4XCMgNBBECk6hLphsyBAUnniz4QSw6AWbiL+KX1oFgbudJD2g17GQ/21fza9Ylyim6pyNsYPablq7L6YGLKsCujMPDVWvz05LUvoSmqWQKRmhc5wQA/R0="


