language: scala

script: sbt +test +package

after_success:
  - >
      test "${TRAVIS_PULL_REQUEST}" = 'false' &&
      test "${TRAVIS_BRANCH}" = 'master' &&
      sh "$TRAVIS_BUILD_DIR/travis_credentials.sh" &&
      sbt +publish