language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  - sbt +geohexJVM/test geohexJS/fullOptJS +geohexJVM/package
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

jdk:
  - openjdk8

after_success: >
  test "${TRAVIS_PULL_REQUEST}" = 'false' &&
  test "${TRAVIS_BRANCH}" = 'master' &&
  sh "$TRAVIS_BUILD_DIR/travis_credentials.sh" &&
  sbt +geohexJVM/publish geohexJS/npmPublish

env:
  global:
    # travis encrypt BINTRAY_USER=teamsigma..
    - secure: "QRtu58P++h+Yr0euCcwR+rs6Vcdc5FThpF7uNeK76lCgOMEx4lxKK5SBqFbgsyNrn0BAiAYKfHCCOBHOsYACWhDeD2anzQc/sUT0YrKA1nF/l5/roifMGaH7IRp2WaHjo/rbcvW31d045jrfx8xmIIzhcfaQYsashgrO7z+4LubUwMh5BMq3PhPAoEru+3Bz+emb18RST4B6z5eSjDRNlFLZslJjhzhMlWhUKFyd69TvUQDZ1BhoaP9nN65cdVrGog1bnD1vHNzC+u8vhrPebzXqlVimFMC6t4nmP87yGZv1nOyfJvF8yEwp/l7lfpREXzbHaLcbSbUdk44GF+pw3WOJqJWmMS9eDchk57zAX7M2CG3PPQp+FEdOfRGgFXBuOTh/XT+JLacwjdG9X/rFnLVeCmboG94xEExc/miYKBgA5lyJ6RYawllVCNZA3CWhlKverwmnLwYOqVIBdlFEIjHhX0kIYhpEY5pVAPUT7cJIBOQTv9Objp4s+jWSP5PJEsx7gmZwZdWxfafFPIncvHFRmMX6Go9UDXsQ3C+ZkH5rZ/LsuT2/bZa3FrmLO61+Urd/HIZqhBkwHNhUm9jhkxtiLxwlomZgqSz+oPteoDsSlgRr3pWXZsvqrg6YfR9Eu2tMLTRqwMNpQWdb9rQNus/qYz16SK5YJNrKpcF1/oU="
    # travis encrypt BINTRAY_PASS=...
    - secure: "CTsejvfa08ijUTWPTbSdS8OUWpPl1a2wCWod0sLPhIsFyG4qt9iJEmOGXuViHUfXZf357lQL9tVwpDtJBQL62YfmO4MqITolZVPoZ68n04FRloKZL35rqWqvLH8FQoJ2wgxeIZPN1QqmbUUatRlZ3XbwWUMtkmulx05ry0hk021WYqJOLJrAFsRLhikNJFPsPLae58ng3CHXwjvICj69PnDtGbPXiaRBW4GnCiNw0VMKHRnZdF4f6bdMUQ1wEqBzYbLX2PB3onbIBNhn3t2OT7f8EgYm7I5joRTui8gdX1RwV2SEnUgfUuzSwxTD5MkF2vVXTsz9Z1bXLnv9A4xOcL8c0102DnoBtpIyOrbex9kKOrAJn0pU0nslhwBFr832peihcB5n0RJ3r1jk2zGveTi713sNcExv3Wdhkx9+NA90Kj+TuozC1P8VRQE/S3BRf1cZ+0a4MpBlGFjksZwzhRkuRmha2RvCVoSGer6pdIG+qKSRsi9MDaYwWtOzOxFigIz+896ssvTut+bQYlEzLz9AVmNApOq6qRZ7oTtaxKUGk0aHfnAQeNqSg9FxpoOgyP4sfaL+XeE0KDq4IIf/KqYRSmVnD0tEjPW1ExoKz/UzAfOYiqiV8RKRFfnRIAFYa3fnEcM5tcdZFKtujlPaHWCL3qF52lAklW+l/6Tzvkg="


